dev env: dev-prep ; sail up ; dev-install

diff --git a/_helpers b/_helpers
--- a/_helpers
+++ b/_helpers
@@ -1,3 +1,24 @@
 
 alias sail='bash vendor/bin/sail'
 
+x.php84 () {
+    ARGS="$@"
+
+    mkdir -p $HOME/.tmp
+
+    docker run -it --rm \
+        -u "$(id -u):$(id -g)" \
+        -v $(pwd):/opt \
+        -v "$HOME/.tmp:/tmp" \
+        -w /opt \
+        laravelsail/php84-composer:latest \
+        /bin/bash -c 'export COMPOSER_HOME=/tmp; export PATH=/opt:$PATH; '"${ARGS}"
+
+    # /bin/bash -c "'${ARGS[*]}'"
+
+    if [[ "$?" != "0" ]]; then
+        echo " !! ERROR !! with ${FUNCNAME[0]}. return code $?";
+        return 1;
+    fi
+    return "$?"
+}
